repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    - id: mixed-line-ending

- repo: https://github.com/bridgecrewio/checkov.git
  rev: master
  hooks:
    - id: checkov
      files: \.tf$

- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: master
  hooks:
    - id: terraform_fmt
    - id: terraform_docs # terraform-docs is not working with Terraform 0.12 yet (read note in README)
